#!/bin/bash

if [ "$1" != "win10" ] && [ "$1" != "win7" ] ; then
    exit 0
fi

#nohup /home/rholk/sbin/vmdata/bindallusb win10 detach 2&
nohup /home/rholk/sbin/switchusb host win10 3 &
disown -h -a
nohup /home/rholk/sbin/lindeskscreen tripple &
disown -h -a
