#!/bin/bash

if [ "$1" != "win10" ] ; then
    exit 0
fi

# removing hugepage
/home/rholk/sbin/hugepagereset
# breaking cgroup shielding
/home/rholk/sbin/shieldbrea-
# let's put back sata controller to ahci
# and nvme drive to nvme
/home/rholk/sbin/bindasmedia ahci

