#!/bin/bash

if [ "$1" != "win10" ] && [ "$1" != "win7" ] ; then
    exit 0
fi
nohup /home/rholk/sbin/switchusb vm win10 wait &
disown -h -a
IP='192.168.88.15' nohup /home/rholk/sbin/lindeskscreen unq&
disown -h -a
