#!/bin/bash

if [ "$1" != "win10" ] && [ "$1" != "win7" ] ; then
    exit 0
fi

/home/rholk/sbin/hugepagereset
/home/rholk/sbin/shieldbreak
/home/rholk/sbin/bindasmedia ahci
#/home/rholk/sbin/powertune
