#!/bin/bash
sudo mkdir /cpuset
sudo mount -t cpuset none /cpuset/
cd /cpuset

echo 0 | sudo tee -a cpuset.cpu_exclusive
echo 0 | sudo tee -a cpuset.mem_exclusive

sudo mkdir sys
echo 'Building shield for core system... threads 0 and 4, and we place all runnning tasks there'
/bin/echo 0,4 | sudo tee -a sys/cpuset.cpus
/bin/echo 0 | sudo tee -a sys/cpuset.mems
/bin/echo 0 | sudo tee -a sys/cpuset.cpu_exclusive
/bin/echo 0 | sudo tee -a sys/cpuset.mem_exclusive
for T in `cat tasks`; do sudo bash -c "/bin/echo $T > sys/tasks">/dev/null 2>&1 ; done
cd -

for D in $(ls /proc/irq)
do
        if [[ -x "/proc/irq/$D" && $D != "0" ]]
        then
#                echo $D
                echo 3 |sudo tee /proc/irq/$D/smp_affinity
        fi
done
# Delay the annoying vmstat timer far away
sudo sysctl vm.stat_interval=120

# Shutdown nmi watchdog as it uses perf events
sudo sysctl -w kernel.watchdog=0

# Pin the writeback workqueue to CPU0
echo 3 | sudo tee /sys/bus/workqueue/devices/writeback/cpumask
